name: Android CI

on:
  pull_request:
    branches-ignore:
      - 'l10n_v3_openjdk2'
    types: [opened, reopened]
  push:
    branches-ignore:
      - 'l10n_v3_openjdk2'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      GPLAY_KEYSTORE_PASSWORD: ${{ secrets.GPLAY_KEYSTORE_PASSWORD }}
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download LTW artifact
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo: PojavLauncherTeam/BigTinyWrapper
          workflow: android.yml
          workflow_conclusion: success
          name: output-aar
          path: app_pojavlauncher/libs

      - name: Download JRE 8
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          path: app_pojavlauncher/src/main/assets/components/jre
          workflow_conclusion: success
          repo: PojavLauncherTeam/android-openjdk-build-multiarch
          branch: buildjre8
          name: jre8-pojav

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: "7.6.1"

      - name: Build with Gradle
        run: |
          ./gradlew :app_pojavlauncher:assembleDebug
          mkdir -p out
          mv app_pojavlauncher/build/outputs/apk/debug/app_pojavlauncher-debug.apk out/

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pojavlauncher-apk
          path: out/app_pojavlauncher-debug.apk
